name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

# Required so the action can push to gh-pages
permissions:
  contents: write

# Avoid overlapping deploys
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # recommended for gh-pages actions

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # For single-page apps (React Router) so deep links work on Pages
      - name: SPA fallback (copy index.html to 404.html)
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          # Optional: set commit author shown on gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
